import { Annotation } from "@langchain/langgraph";

export const SearchState = Annotation.Root({
  // The original user question — never mutated
  question: Annotation<string>(),

  // Sub-queries generated by the planner. Reducer appends across iterations.
  queries: Annotation<string[]>({
    reducer: (a, b) => [...a, ...b],
    default: () => [],
  }),

  // Raw search results accumulated across all iterations
  results: Annotation<{ query: string; content: string; url?: string }[]>({
    reducer: (a, b) => [...a, ...b],
    default: () => [],
  }),

  // Latest reflection text (overwritten each iteration)
  reflection: Annotation<string>(),

  // Final synthesized answer
  answer: Annotation<string>(),

  // Iteration counter — used to enforce MAX_ITERATIONS
  iterations: Annotation<number>({
    reducer: (_, b) => b,
    default: () => 0,
  }),
});

export type SearchStateType = typeof SearchState.State;
